// Ekstrahert fra Shop.jsx for bruk i gave-disguise
const shopItems = [
  // POTION INGREDIENTS & EQUIPMENT (for Potions class)
  {
    id: 599,
    name: "Moonstone Dust",
    price: 22,
    type: "ingredient",
    category: "Ingredients",
    description:
      "Glittering dust from a moonstone, enhances clarity in potions.",
    effect: "Used in advanced potion making.",
  },
  {
    id: 501,
    name: "Rose Petals",
    price: 12,
    type: "ingredient",
    category: "Ingredients",
    description: "Fragrant petals, essential for love potions.",
    effect: "Used in potion making.",
  },
  {
    id: 502,
    name: "Unicorn Hair",
    price: 25,
    type: "ingredient",
    category: "Ingredients",
    description: "Rare magical hair, amplifies potion effects.",
    effect: "Used in potion making.",
  },
  {
    id: 503,
    name: "Sugar",
    price: 5,
    type: "ingredient",
    category: "Ingredients",
    description: "Sweetens and stabilizes magical brews.",
    effect: "Used in potion making.",
  },
  {
    id: 504,
    name: "Raspberries",
    price: 8,
    type: "ingredient",
    category: "Ingredients",
    description: "Juicy berries, add flavor and color.",
    effect: "Used in potion making.",
  },
  {
    id: 505,
    name: "Magical Water",
    price: 15,
    type: "ingredient",
    category: "Ingredients",
    description: "Water from a magical spring, base for many potions.",
    effect: "Used in potion making.",
  },
  {
    id: 506,
    name: "Hidden Mushrooms",
    price: 18,
    type: "ingredient",
    category: "Ingredients",
    description: "Rare fungi found in shadowy forests.",
    effect: "Used in potion making.",
  },
  {
    id: 507,
    name: "Dragon Blood",
    price: 40,
    type: "ingredient",
    category: "Ingredients",
    description: "Powerful magical catalyst, handle with care!",
    effect: "Used in potion making.",
  },
  {
    id: 508,
    name: "Stardust",
    price: 22,
    type: "ingredient",
    category: "Ingredients",
    description: "Sparkling dust from a shooting star.",
    effect: "Used in potion making.",
  },
  {
    id: 509,
    name: "Shadow Leaf",
    price: 14,
    type: "ingredient",
    category: "Ingredients",
    description: "A leaf that absorbs light, used for invisibility.",
    effect: "Used in potion making.",
  },
  {
    id: 510,
    name: "Blackcurrant",
    price: 10,
    type: "ingredient",
    category: "Ingredients",
    description: "Tart berry, boosts energy in elixirs.",
    effect: "Used in potion making.",
  },
  {
    id: 511,
    name: "Phoenix Feather",
    price: 35,
    type: "ingredient",
    category: "Ingredients",
    description: "Rare feather, infuses potions with vitality.",
    effect: "Used in potion making.",
  },
  {
    id: 512,
    name: "Honey",
    price: 7,
    type: "ingredient",
    category: "Ingredients",
    description: "Sweet and magical, binds ingredients together.",
    effect: "Used in potion making.",
  },
  {
    id: 513,
    name: "Magical Herb",
    price: 13,
    type: "ingredient",
    category: "Ingredients",
    description: "A mysterious herb with energizing properties.",
    effect: "Used in potion making.",
  },
  {
    id: 514,
    name: "Silver Leaf",
    price: 16,
    type: "ingredient",
    category: "Ingredients",
    description: "Shimmery leaf, reveals hidden truths.",
    effect: "Used in potion making.",
  },
  {
    id: 515,
    name: "Amber",
    price: 20,
    type: "ingredient",
    category: "Ingredients",
    description: "Fossilized resin, stabilizes truth serums.",
    effect: "Used in potion making.",
  },
  {
    id: 516,
    name: "Troll Berries",
    price: 11,
    type: "ingredient",
    category: "Ingredients",
    description: "Berries favored by trolls, potent in potions.",
    effect: "Used in potion making.",
  },
  {
    id: 517,
    name: "Magical Salt",
    price: 9,
    type: "ingredient",
    category: "Ingredients",
    description: "Salt with magical properties, purifies brews.",
    effect: "Used in potion making.",
  },
  // Equipment for advanced potions
  {
    id: 518,
    name: "Silver Cauldron",
    price: 180,
    type: "equipment",
    category: "Equipment",
    description: "A cauldron made of pure silver, required for advanced brews.",
    effect: "Required for brewing truth serums.",
  },
  // BOOKS
  {
    id: 201,
    name: "Standard Book of Spells",
    price: 80,
    type: "book",
    category: "Books",
    description:
      "A must-have for every young witch or wizard. Unlocks new spells.",
    effect: "Unlocks basic spells.",
  },
  {
    id: 202,
    name: "Magical Theory",
    price: 60,
    type: "book",
    category: "Books",
    description:
      "Learn the theory behind magic. Required for advanced classes.",
    effect: "Required for advanced classes.",
  },
  // INGREDIENTS
  {
    id: 301,
    name: "Unicorn Hair",
    price: 25,
    type: "ingredient",
    category: "Ingredients",
    description: "Rare potion ingredient. Used in powerful brews.",
    effect: "Used in potion making.",
  },
  {
    id: 302,
    name: "Mandrake Root",
    price: 18,
    type: "ingredient",
    category: "Ingredients",
    description: "Essential for restorative potions.",
    effect: "Used in potion making.",
  },
  // EQUIPMENT
  {
    id: 401,
    name: "Wand",
    price: 250,
    type: "equipment",
    category: "Equipment",
    description: "Channel your magic. Required for spellcasting.",
    effect: "Allows spellcasting.",
  },
  {
    id: 402,
    name: "Cauldron",
    price: 120,
    type: "equipment",
    category: "Equipment",
    description: "Brew potions and experiment with ingredients.",
    effect: "Required for potion making.",
  },
  {
    id: 123,
    name: "Love Potion",
    price: 150,
    type: "potion",
    category: "Potions",
    description:
      "A magical pink potion. If gifted and consumed, the drinker falls in love with the giver for 20 minutes! Hearts rain on their screen, their profile glows pink, and everyone can see who they're in love with.",
    effect: "In love with the giver for 20 minutes.",
  },
  // GENERIC FOOD ITEMS (non-Harry Potter themed)
  {
    id: 1001,
    name: "Apple",
    price: 8,
    type: "food",
    category: "Food",
    description: "A fresh apple. Restores 15 health.",
    effect: "+15 health",
    health: 15,
  },
  {
    id: 1002,
    name: "Sandwich",
    price: 40,
    type: "food",
    category: "Food",
    description: "A hearty sandwich. Restores 40 health.",
    effect: "+40 health",
    health: 40,
  },
  {
    id: 1003,
    name: "Salad",
    price: 15,
    type: "food",
    category: "Food",
    description: "A bowl of fresh salad. Restores 20 health.",
    effect: "+20 health",
    health: 20,
  },
  {
    id: 1004,
    name: "Pizza Slice",
    price: 35,
    type: "food",
    category: "Food",
    description: "A cheesy pizza slice. Restores 32 health.",
    effect: "+32 health",
    health: 32,
  },
  {
    id: 1005,
    name: "Cookie",
    price: 6,
    type: "food",
    category: "Food",
    description: "A sweet cookie. Restores 10 health.",
    effect: "+10 health",
    health: 10,
  },
  {
    id: 1006,
    name: "Orange Juice",
    price: 18,
    type: "food",
    category: "Food",
    description: "A glass of orange juice. Restores 18 health.",
    effect: "+18 health",
    health: 18,
  },
  {
    id: 4,
    name: "Healing Potion",
    price: 200,
    type: "potion",
    category: "Potions",
    description:
      "Restores your character's health to full. On the website: Shows a healing animation and a message.",
    effect: "Fully restores health.",
  },
  {
    id: 98,
    name: "Death Draught",
    price: 10,
    type: "potion",
    category: "Potions",
    description:
      "A dangerous potion for testing. Sets your health to 0 instantly.",
    effect: "Sets health to 0 (for testing infirmary)",
  },
  {
    id: 5,
    name: "Invisibility Draught",
    price: 110,
    type: "potion",
    category: "Potions",
    description:
      "Makes you invisible to others for 5 minutes. On the website: You disappear from the online list and your avatar is faded.",
    effect: "Invisible for 5 minutes.",
  },
  // NEW VISUAL EFFECT POTIONS
  {
    id: 600,
    name: "Hair Color Potion",
    price: 45,
    type: "potion",
    category: "Potions",
    description: "Changes your chat text to a random color for 2 hours.",
    effect: "Random chat text color for 2 hours.",
  },
  {
    id: 601,
    name: "Rainbow Potion",
    price: 60,
    type: "potion",
    category: "Potions",
    description: "Your chat text changes color every 10 seconds for 1 hour.",
    effect: "Rainbow chat text for 1 hour.",
  },
  {
    id: 602,
    name: "Glow Potion",
    price: 55,
    type: "potion",
    category: "Potions",
    description: "Makes your name glow in chat for 3 hours.",
    effect: "Glowing name in chat for 3 hours.",
  },
  {
    id: 603,
    name: "Sparkle Potion",
    price: 50,
    type: "potion",
    category: "Potions",
    description: "Sparkles float around your avatar for 2 hours.",
    effect: "Sparkles around avatar for 2 hours.",
  },
  // CHAT EFFECT POTIONS
  {
    id: 604,
    name: "Translation Potion",
    price: 70,
    type: "potion",
    category: "Potions",
    description: "All messages are translated to random languages for 2 hours.",
    effect: "Random language translation for 2 hours.",
  },
  {
    id: 605,
    name: "Echo Potion",
    price: 40,
    type: "potion",
    category: "Potions",
    description: "All your messages are sent twice for 1 hour.",
    effect: "Echo messages for 1 hour.",
  },
  {
    id: 606,
    name: "Whisper Potion",
    price: 35,
    type: "potion",
    category: "Potions",
    description: "You can only send private messages for 2 hours.",
    effect: "Private messages only for 2 hours.",
  },
  {
    id: 607,
    name: "Shout Potion",
    price: 30,
    type: "potion",
    category: "Potions",
    description: "All your messages are in CAPS for 15 minutes.",
    effect: "CAPS messages for 15 minutes.",
  },
  // UI EFFECT POTIONS
  {
    id: 608,
    name: "Dark Mode Potion",
    price: 80,
    type: "potion",
    category: "Potions",
    description: "Changes the entire website to dark mode for 4 hours.",
    effect: "Dark mode for 4 hours.",
  },
  {
    id: 609,
    name: "Retro Potion",
    price: 45,
    type: "potion",
    category: "Potions",
    description: "Changes all fonts to retro style for 2 hours.",
    effect: "Retro fonts for 2 hours.",
  },
  {
    id: 610,
    name: "Mirror Potion",
    price: 65,
    type: "potion",
    category: "Potions",
    description: "Flips the entire website horizontally for 2 hours.",
    effect: "Mirrored website for 2 hours.",
  },
  // FUNCTIONALITY POTIONS
  {
    id: 611,
    name: "Speed Potion",
    price: 55,
    type: "potion",
    category: "Potions",
    description: "All animations run 2x faster for 15 minutes.",
    effect: "2x faster animations for 15 minutes.",
  },
  {
    id: 612,
    name: "Slow Motion Potion",
    price: 50,
    type: "potion",
    category: "Potions",
    description: "All animations run 0.5x slower for 1 hour.",
    effect: "0.5x slower animations for 1 hour.",
  },
  {
    id: 613,
    name: "Lucky Potion",
    price: 90,
    type: "potion",
    category: "Potions",
    description: "Doubles your chance of getting rare items for 3 hours.",
    effect: "2x rare item chance for 3 hours.",
  },
  {
    id: 614,
    name: "Wisdom Potion",
    price: 200,
    type: "potion",
    category: "Potions",
    description: "Gives extra points for all actions for 2 hours. Very expensive!",
    effect: "Extra points for all actions for 2 hours.",
  },
  // SURVEILLANCE POTION
  {
    id: 615,
    name: "Surveillance Potion",
    price: 120,
    type: "potion",
    category: "Potions",
    description: "See what all users are doing and where they are on the website for 1 hour.",
    effect: "See all user activities for 1 hour.",
  },
  // SOCIAL EFFECT POTIONS
  {
    id: 616,
    name: "Charm Potion",
    price: 75,
    type: "potion",
    category: "Potions",
    description: "Other users see you as more attractive with special icons for 2 hours.",
    effect: "Attractive appearance for 2 hours.",
  },
  {
    id: 617,
    name: "Mystery Potion",
    price: 60,
    type: "potion",
    category: "Potions",
    description: "Your name appears as '???' to other users for 2 hours.",
    effect: "Mysterious name for 2 hours.",
  },
];

export default shopItems;
