// Ekstrahert fra Shop.jsx for bruk i gave-disguise
const shopItems = [
  // POTION INGREDIENTS & EQUIPMENT (for Potions class)
  {
    id: 599,
    name: "Moonstone Dust",
    price: 22,
    type: "ingredient",
    category: "Ingredients",
    description:
      "Glittering dust from a moonstone, enhances clarity in potions.",
    effect: "Used in advanced potion making.",
  },
  {
    id: 501,
    name: "Rose Petals",
    price: 12,
    type: "ingredient",
    category: "Ingredients",
    description: "Fragrant petals, essential for love potions.",
    effect: "Used in potion making.",
  },
  {
    id: 502,
    name: "Unicorn Hair",
    price: 25,
    type: "ingredient",
    category: "Ingredients",
    description: "Rare magical hair, amplifies potion effects.",
    effect: "Used in potion making.",
  },
  {
    id: 503,
    name: "Sugar",
    price: 5,
    type: "ingredient",
    category: "Ingredients",
    description: "Sweetens and stabilizes magical brews.",
    effect: "Used in potion making.",
  },
  {
    id: 504,
    name: "Raspberries",
    price: 8,
    type: "ingredient",
    category: "Ingredients",
    description: "Juicy berries, add flavor and color.",
    effect: "Used in potion making.",
  },
  {
    id: 505,
    name: "Magical Water",
    price: 15,
    type: "ingredient",
    category: "Ingredients",
    description: "Water from a magical spring, base for many potions.",
    effect: "Used in potion making.",
  },
  {
    id: 506,
    name: "Hidden Mushrooms",
    price: 18,
    type: "ingredient",
    category: "Ingredients",
    description: "Rare fungi found in shadowy forests.",
    effect: "Used in potion making.",
  },
  {
    id: 507,
    name: "Dragon Blood",
    price: 40,
    type: "ingredient",
    category: "Ingredients",
    description: "Powerful magical catalyst, handle with care!",
    effect: "Used in potion making.",
  },
  {
    id: 508,
    name: "Stardust",
    price: 22,
    type: "ingredient",
    category: "Ingredients",
    description: "Sparkling dust from a shooting star.",
    effect: "Used in potion making.",
  },
  {
    id: 509,
    name: "Shadow Leaf",
    price: 14,
    type: "ingredient",
    category: "Ingredients",
    description: "A leaf that absorbs light, used for invisibility.",
    effect: "Used in potion making.",
  },
  {
    id: 510,
    name: "Blackcurrant",
    price: 10,
    type: "ingredient",
    category: "Ingredients",
    description: "Tart berry, boosts energy in elixirs.",
    effect: "Used in potion making.",
  },
  {
    id: 511,
    name: "Phoenix Feather",
    price: 35,
    type: "ingredient",
    category: "Ingredients",
    description: "Rare feather, infuses potions with vitality.",
    effect: "Used in potion making.",
  },
  {
    id: 512,
    name: "Honey",
    price: 7,
    type: "ingredient",
    category: "Ingredients",
    description: "Sweet and magical, binds ingredients together.",
    effect: "Used in potion making.",
  },
  {
    id: 513,
    name: "Magical Herb",
    price: 13,
    type: "ingredient",
    category: "Ingredients",
    description: "A mysterious herb with energizing properties.",
    effect: "Used in potion making.",
  },
  {
    id: 514,
    name: "Silver Leaf",
    price: 16,
    type: "ingredient",
    category: "Ingredients",
    description: "Shimmery leaf, reveals hidden truths.",
    effect: "Used in potion making.",
  },
  {
    id: 515,
    name: "Amber",
    price: 20,
    type: "ingredient",
    category: "Ingredients",
    description: "Fossilized resin, stabilizes truth serums.",
    effect: "Used in potion making.",
  },
  {
    id: 516,
    name: "Troll Berries",
    price: 11,
    type: "ingredient",
    category: "Ingredients",
    description: "Berries favored by trolls, potent in potions.",
    effect: "Used in potion making.",
  },
  {
    id: 517,
    name: "Magical Salt",
    price: 9,
    type: "ingredient",
    category: "Ingredients",
    description: "Salt with magical properties, purifies brews.",
    effect: "Used in potion making.",
  },
  // Equipment for advanced potions
  {
    id: 518,
    name: "Silver Cauldron",
    price: 180,
    type: "equipment",
    category: "Equipment",
    description: "A cauldron made of pure silver, required for advanced brews.",
    effect: "Required for brewing truth serums.",
  },
  // BOOKS
  {
    id: 201,
    name: "Standard Book of Spells",
    price: 80,
    type: "book",
    category: "Books",
    description:
      "A must-have for every young witch or wizard. Unlocks new spells.",
    effect: "Unlocks basic spells.",
  },
  {
    id: 202,
    name: "Magical Theory",
    price: 60,
    type: "book",
    category: "Books",
    description:
      "Learn the theory behind magic. Required for advanced classes.",
    effect: "Required for advanced classes.",
  },
  // INGREDIENTS
  {
    id: 301,
    name: "Unicorn Hair",
    price: 25,
    type: "ingredient",
    category: "Ingredients",
    description: "Rare potion ingredient. Used in powerful brews.",
    effect: "Used in potion making.",
  },
  {
    id: 302,
    name: "Mandrake Root",
    price: 18,
    type: "ingredient",
    category: "Ingredients",
    description: "Essential for restorative potions.",
    effect: "Used in potion making.",
  },
  // EQUIPMENT
  {
    id: 401,
    name: "Wand",
    price: 250,
    type: "equipment",
    category: "Equipment",
    description: "Channel your magic. Required for spellcasting.",
    effect: "Allows spellcasting.",
  },
  {
    id: 402,
    name: "Cauldron",
    price: 120,
    type: "equipment",
    category: "Equipment",
    description: "Brew potions and experiment with ingredients.",
    effect: "Required for potion making.",
  },
  {
    id: 123,
    name: "Love Potion",
    price: 150,
    type: "potion",
    category: "Potions",
    description:
      "A magical pink potion. If gifted and consumed, the drinker falls in love with the giver for 20 minutes! Hearts rain on their screen, their profile glows pink, and everyone can see who they're in love with.",
    effect: "In love with the giver for 20 minutes.",
  },
  {
    id: 20,
    name: "Chocolate Frog",
    price: 30,
    type: "food",
    category: "Food",
    description: "A magical treat that restores 15 health.",
    effect: "+15 health",
  },
  {
    id: 21,
    name: "Pumpkin Pastie",
    price: 25,
    type: "food",
    category: "Food",
    description: "A sweet pumpkin-filled pastry. Restores 10 health.",
    effect: "+10 health",
  },
  {
    id: 22,
    name: "Butterbeer",
    price: 20,
    type: "food",
    category: "Food",
    description: "A frothy drink that restores 8 health.",
    effect: "+8 health",
  },
  {
    id: 4,
    name: "Healing Potion",
    price: 200,
    type: "potion",
    category: "Potions",
    description:
      "Restores your character's health to full. On the website: Shows a healing animation and a message.",
    effect: "Fully restores health.",
  },
  {
    id: 98,
    name: "Death Draught",
    price: 10,
    type: "potion",
    category: "Potions",
    description:
      "A dangerous potion for testing. Sets your health to 0 instantly.",
    effect: "Sets health to 0 (for testing infirmary)",
  },
  {
    id: 5,
    name: "Invisibility Draught",
    price: 110,
    type: "potion",
    category: "Potions",
    description:
      "Makes you invisible to others for 5 minutes. On the website: You disappear from the online list and your avatar is faded.",
    effect: "Invisible for 5 minutes.",
  },
];

export default shopItems;
